server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息：
        defaultRabbit: # 表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名词是一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称定义s
          content-type: application/json  #设置消息类型，本次为json,文本则设置"text/plain"
          binder: defaultRabbit  #设置要绑定的消息服务的具体设置
          #相同分组可以避免重复消费，如果不加对于持久化消费也失效
          group: yeafelA
eureka:
  client:  #客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2  #设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
    instance-id: receive-8802.com  #在信息列表时显示主机名称
    prefer-ip-address: true #访问的路径变为IP地址
