server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&chracterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yeafel.springcloud.entities     #所在Entity别名类所在包

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
  instance:
    instance-id: payment8002
    prefer-ip-address: true     #访问路径可以显示ip地址